# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build ./src/SoftwareTesting.sln --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
  condition: 
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: './src/XUnitExamples/XUnitExamples.csproj'
  displayName: 'XUnirExamples'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: './src/Playwright/Playwright.csproj'
  displayName: 'Playwright'
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: './src/DALIntegrationTests/DALIntegrationTests.csproj'
  displayName: 'DALIntegration'
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: './src/DALSample/DALSample.csproj'
  displayName: 'DALSample'
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: './src/MachineSpecifications/MachineSpecifications.csproj'
  displayName: 'MachineSpecification'
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: './src/Mocking/Mocking.csproj'
  displayName: 'Mocking'
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: './src/PlaywrightTests/PlaywrightTests.csproj'
  displayName: 'PlaywrightTests'